using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyCompanyAttribute("Andy Pike")]
[assembly: AssemblyProductAttribute("Castlecasts.com Website")]
[assembly: AssemblyVersionAttribute("1.0.0.1")]
[assembly: AssemblyCopyrightAttribute("Copyright (c)2009 Andy Pike. All Rights Reserved.")]

